apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-app
  namespace: prodesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-app
  template:
    metadata:
      labels:
        app: asset-app
    spec:
      enableServiceLinks: false
      containers:
      - name: asset-app
        image: ghcr.io/sijunkim/asset-app:master-placeholder
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: asset-app-secret
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=75"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
