apiVersion: v1
kind: Secret
metadata:
    name: dama-mysql-datasource
    namespace: monitoring
    labels:
        grafana_datasource: "1"
type: Opaque
stringData:
    dama-mysql-datasource.yaml: ENC[AES256_GCM,data:xNfALv3YHkp34GeeA/mf2WQFm75mEfVIn5fKr2Q/U6bKNZBNGinhQY27hISmoaZuXw7tHk2nmgkdeKaRGMjW3A/EPewRQTUaScD27a9qPlkYvnddCfBhYxDKZaiLMlY9Nxx9ar0AsK4VNKpxnL9//Wi6RpJ2mwhvN6xQheSucAKVUbAKV6wNEfqRikWVKX59iNKXTA3Szj6rj00zycn6J0XJr7KzinXibXjwa8sLKWfzfvlMKi49lknDHMP/C26F4QgVOzsPH5fqzTlvMrqq37TRUE+VhDPicuO+8s/gYXVODjJ06es07Hgu6reyznBeSEV0JnEkvRJ1mT/draah/Wni0eKze+o7EzrKtE5RXNX4IYBWjqM+nnf87UhL7whzr9Cq0A+84vzPyaFChWIO4clGLxlmKMAYAgLuRimkBgyykv+xzLQe6BTabF8j2XKcIdeR/LScuGnpqs0mDpMt40nhrT+hHg/5EbZNS03OWu5HyG2p9p3awkX4FT0NVZeF7JHPKlzWpVSvJMs=,iv:MosYCabt/gAx8etF/oVW/Ha2lBpwJ5f2fEoVf9XKX1Y=,tag:Etsi/jJVBpCN9D4AkbtFmQ==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZGN6OVJTY2JtT0pHcjFs
            RFFhR3RpR0t5YnI4YzJSUktKSzJRZzFkdlFzCm4vZkFwbnpUWm44RUkrUlhFR2l3
            aCtRVmhuK1JyTHdqSkN4TUNzV3E0a1kKLS0tIEZjNEh6NjlrTERTZWlQK0ZYN1J1
            OE1uTzFyQ29FbEJXNDF5YThET0EwN2MKxom0YhFxrs5A0N50ewZVGyYTnHcnfgLq
            eL4J3m/7ic2BhNDOMmZUHSqGu98TyOlFm7BtfVxIz0BMrp26d/f05A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T15:22:34Z"
    mac: ENC[AES256_GCM,data:Eob5eNF/Mb3m6YpVjwNBLDQFcTPSEvTS2130AWHJiePSfxitmIIyUxCMLtWS911bdEb8GHoOaE02FuxyEGsobfL2Y1mYk6Dt4ydmJiw3/VYTsONO5JO2NScLmsw3CCNjLM8+g9mFzmk1c1s9DQ4kvaP1MAvLMqzLfHpnOuiOSHY=,iv:530L4OTb0ZsBk+cHcPImZO9WuImWIRQUNSwKImrzGZ0=,tag:L1kkmwHCBzp1FFF32rTAYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
