apiVersion: v1
kind: Secret
metadata:
    name: friend-app-secret
    namespace: prodesk
type: Opaque
stringData:
    ASSETS_TOKEN: ENC[AES256_GCM,data:qwjEuOl2icu1hrye/vsQ4MulscCAoTnxxqIAvZv6uNFN6s0LEIpZglhw6inrqRGF+FqcjLNjyLROLHF4vqoMjg==,iv:TT+84eWPr19Pipe3faRkJimTB4sh9iNky/xaupmEb6s=,tag:JZbhuUPGko0B6kCfd5UgHQ==,type:str]
    ACCOUNTS_JSON: ENC[AES256_GCM,data:9huyNAbpR0BrQ6PPg6RBqI/kzIhyRNCICqvmMMBEHAJGz4KeOZ+It18L+hXdv2bATyH2QqTx4djgh0Y19xiD0BWsV8bX+Ild9bC9maaatvn4coZhJoK8Fa41fZ/jyS555Rm3qTl6+HImWF0bXuRqkQxVvCO7vHfKWY57HiEVZchkL77WAwZGqp83hiTpuMLi65Zw95XZh5NvYx6xMbVjZikTaqz8fm6RuEeStFwLSWzCLE7x2nse2LHhVZ8FME7i/9e/1O/IvOyeSuQcUMkNg/X1+eGtY4k6+eyug7XRL3WWHUIR2K686nDMJhwF+clb2eIC7OamehExY8NXHi9+oYun41TYZ5xqFIMuD1WeytIL2YHIXbTFKqA53hs0eKtRf+xgRyi0jPmDGxuWOffLXXp4WtyBsHaCdXjwI7SrkJXrqmDcd1F7beuKNRAsjA/9o4KQJuWqqot1UUieJ3qZYbV4jpnXLqtetS0pJrwp73DK+h9ea1mdmJYii1d9nA3Mjf0wOoYYDLvcIsggDxNC+BQrnSRW9/LznmQSAqCNqqD1q7FmkEgwb7o3HQyHzlgcJ4EJWuMHMWFWhtFVkhnd3AYEULbneWwElOz6Is/4DNocOe+GC7pkmRC4vIMC7E6815L57tZDSczENqpMKDCTQch1tISESQOG+9ASyJ1yPHbayHbmcwT0xhPFWNXlCBDpnC1KCZXJRGu5069ZMGh0IixtaocVlAwbTD1TmiNMaibqSiFWCHJrzby/JYH0xpnH+1P6c7kBTiNym3gdalToe/P8RXvpp4XeEfWIzD4JBlbdyyXsTpWc++VW2g12FoZqI854M7mCw/q4kUH+TAXEF8U6fl4CSRTw3Hzw79Qeb1rmnVL3l9yd9mgAHwfHP/XhcvrMzqq8vdyH5UeKJsNMyG1z7hyIjP0jUs/og/mADH9B0Q58p8wZ49daE1jBQIfRjolx80TNEv0pueN3wScirLbXELyq8ly4jrKLcxWGzmgLKOjcZg7DQxYY+KzGbIvlEuFv/aa1IXzGWrVtvDLTjC6+mAZeMXSwLurIKJ4zaTOKHoS0qKKsXn9YWEXNmL5cx9iGglWWWBHTjXMk87Wie/31j0Q+gKVChwbKbiX2j/ktOPgoGSUhmOmLohm1yq79NsB1fXaFqSSnfVCl/zc8B3y5,iv:9YwJ7xVb7HZKZo6oiBViTy/qZ4Ip0QIk++eDy+Ye/Zc=,tag:bwZbueae16CMpN0fDjcOwA==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM3lKUFpKNUdqaFh6YmFQ
            VHpkK2wrR2xKeHI0bE0wZXRXaHNQQ3RDUkhvCmExTTd2VGNOZ0VKaUhKb1I4UmZN
            SS9HY0w0RldZMFFzM0h4aVgwQ2pVaWMKLS0tIFIySDEvcmdSS1I3VGZTV1o1aCtU
            N0JFNFVYUmExUFpiY0czcldESnBJcmMKQHA2Ai62WdDXwsHncMSpjt+YDyZk0Bbi
            p8vWwtorymS9AKTL5bi/t4/IpbLZK6LfmX2Um0BHyO1MW8XUa56nwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T13:58:17Z"
    mac: ENC[AES256_GCM,data:MKu8UmdqMILJumBv0Hzy6I2nWdudrqeXCZo/SMtDdwMvgOUeDTMbOriLTpW1rqG/ma6U2e0gKqDyGrcBJJE0D0ntOwv6ZHX2ZeTRJ6juMvOM0Sa6uXxwD9TOf3jAbpN1PLUbOdalaC1/+UKW0hoe68lBXPMkIbyrGisl35WIp0c=,iv:p0Epw+XvSk3QdfefAKnObxOVrn7rKk8IyCVszDrtE+M=,tag:RiDVExr1R4tLxo3lsXtI9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
