apiVersion: v1
kind: Secret
metadata:
    name: dama-api-secret
    namespace: prodesk
type: Opaque
stringData:
    SLACK_SIGNING_SECRET: ENC[AES256_GCM,data:YXuvLkg4gAe3Lg==,iv:Y7/QLZckFLL98YP+zyJ3XJDSSMzO4VRkR18X40sNpxM=,tag:Ol0DePEmETv7/m5yUyTZYw==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:lQsEAS/NooTtfg==,iv:2N/2kwgtmi3Ljpm8fnDbjEoR0h3cuM24OC9r8UZOs0c=,tag:jYYlTEtpRnLoNraGEcMi8A==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOXBkMlA1VWZtLzdiTjd2
            ZGZFOVBiN3JQYVZQTGVkbUZmY0xTL0hBSXhNCm9rZVFTOVNtaDJWT3lyYmxPajkx
            YjViSVFCNG42MlMybHFVYTlzWkRSR3cKLS0tIHVhVVlMN01xTTdGbUpnQ2VIUjc1
            dEk2Y2gyeGgrK2pBUmNGWTlNV3hOMlkK1qYRvcIU49nIwYh5zTSYMEeI+HSiBP4f
            sQEE+FRagebMtz6yB1rrFJsPpsGJEhJYyPY5mU3UsQkq2g7ch5AJdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-10T16:31:56Z"
    mac: ENC[AES256_GCM,data:SL3B79e6bA+6RmyLiJ+yQ77dM7SNvRa4a0yI1o+uT8rE5oyEH+eHrc23EsJBmQG/7vDsUcLZirEdoEf7HFVYDh/pN3OmeFm+OS0nkZNL3XuLMx37HWNPRJnKjfZUL7CbagbAWxLdFwWluO6tDKFgz4bvIQ68dq4uDdgLODT2nlA=,iv:CnKq4Efnci5uvhle45ywICXfqZ4Gq+c5SGlkSESzFfU=,tag:UGwCblpMqeSmHMpcbeiNaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
