apiVersion: v1
kind: Secret
metadata:
    name: dama-api-secret
    namespace: prodesk
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:CUzmWrydOXT9/5LNE+l49kmgJfOGrUXc8+hpHN07n6TB+5viQD+SKBUE/pzmVqWWWKaSgUoJjDsMZCtmKh3RU3msAmeQWcco,iv:WMVdyNmiB7OQ4SwvX5Zb3HcvcdikLu9IFDADeyc0RFg=,tag:SKIwjcCiRjfroprisZqxHg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:1zwaYavCB2ybBGEXcwOfOfWxuPOnagvwpqkkq64dUmQP2ZvtTM4R6Tmyf61hAybR5lQ36+RAxosUkOn7qrDyMw==,iv:r7YLC/GpBCOHE3AIVvWwu0FjTIOJ688LNVasSdkCv0c=,tag:VQULpuktNywNsQjd9dSNuw==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN2phd0ZNbFdWT1p2a1A3
            cXJoZ3hhcnFJcGgwTzNLSFpHMlQwM2dRWXpjCjRzOXlJNFFVMndjRnF3RjZPckQ5
            R1ZjWEMvOG54Z0dZRGFVbXhnSHlTS00KLS0tIHlhUzJBV0dydHFCQlhaRXpBcWZu
            M2tkZHVsT2ppWlRNUDlDY09VZFlQelkKZ9gC7jReI0bUlb3OD+GX5mNfk6T3bJZE
            nVIPx1vPROT4WL84IRGk6IDP0jOc+/cMTZyhLkQcRm80TqtsTc3AEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T07:32:20Z"
    mac: ENC[AES256_GCM,data:5SnYpH79Uc38xz0yUv4RngOBlLy4H1qngUd+JjmJWdOyLJKGn2IctE+/zEhqG/a04Vs6/Mwf7uLdSQ+Jq8Xs5EH/p+4vMimdKFx7M8nd/qs5U9uxjANK2w1RS9Qp9Kr1fL6Ml/dMXqpY+hW8fMnFWWi8VEolvVSSsOavkSQniVM=,iv:8ksdTvVaMmq6VnYUd6f4oxYvuc4DQy0Eur8EVPULDaM=,tag:r6vABD3Dy++aqidRzVspiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
