apiVersion: v1
kind: Secret
metadata:
    name: dama-api-secret
    namespace: prodesk
type: Opaque
stringData:
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:+cOho8bC1HNSOsASQRwsimftG2pWn8ORMQVjRhz7IcanYC+fP1vu2rZkoJFRtyCKg1fIMlbl5umqJr8zQA4yzUOlYcNPcEXb,iv:OVcGBO/zmtJSS3lL8jBwl5+wsb36AVzG6y+lxFrgwkA=,tag:Ixmz0UPQjDz+cuQQclF9Bg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:+Ktc5NE3nQavvaQ8OP4WKMeCNslARAhoVfH6+gFPstBHwp4hal4eBP3gT/9iaVD+9z76Ll0c//1iUVqF+UfEUg==,iv:rM1+5Z0hL44jwoM2hYJKpD6KQUhHwpPkAiOW9FwZmV4=,tag:YfkqI/lnJBwforWMPgQxVg==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:eDFudf3dLjJNNfS3HaD3og3rP1/i+UM5wquQ4utgxaaJQmkVr/vYTyE3eO/hWSi4tdMvthENUbc=,iv:cMANIaSpvgUPv3afIhQoCVQM+9GHK1liCMec3VThmvY=,tag:g9imlC2T4V8VRJhYldaiMQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:dpHgdJycPJo9dNzm5vrneQS/cOobo5rS7XIO8N9ir4GVluX4P7Fuqw7dnjr9mhN4XtUjREo=,iv:CyR2aGO0WFlAAVMtzBZ4IQHuReXwJa071MNdQhfUp5Y=,tag:0EsJO2+JA8wlTFosi30MXw==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:aT0/HtIUHJfjr/cC+Tezbwaa6BcLRNxs2Q==,iv:v1wV2J3PEE4Lj5lkufn/eKms+ejdRi43QJHmyzMPZuI=,tag:b7s1nN6nQu2+81Yte+1z3Q==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:Z5H0sxr15x7GLvzNggPNpA==,iv:C6fac0HylPFmxSeJvEAneaCeiCq7CWWLGVGa6TXYaOM=,tag:UY/tYGczJS1VE9PLZHaQDw==,type:str]
    SLACK_WEBHOOK_ENABLED: ENC[AES256_GCM,data:cxr90Q==,iv:MHHccB9ndMmZ24rljyMXH4DseKpA27RL3binVCDI2yc=,tag:djfTqGEVRPlYqpDkFOD/6w==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:u1fVqDH7l8tma0j76U/5hAzxsh9klI0ofn7ZC/ou0D/DCTVPxKydxp9UC/r+9LaG7LurinN0zhCnzPEF9Y3fdqvXk/90bJtOLgUhuDANU2UE,iv:cC9Kj3rHawZ0UXSZ5okoDM4Vprw8Shr1C73bXoC3kGA=,tag:tR9W2a79HWd413BiNpRZ6Q==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc3hOdmhNQ0pEbmVTamlu
            YUJoVWNJRmlsUG9TbkRmOC9kem9xVjhJTXdnCjh3QmZoMWNveXhXakpodHBIRTlS
            SVNTRFVHUUROQVQ4TEtqcWlicWdCclUKLS0tIE9BVWszaDFoZjdabC8rOU1MdmVZ
            RXYrYmNlTkUyc2FTRkJ0aTNRM3ZOSncKJspfgKke3rR8syN2B3kmbCNevYtABmew
            alRlUfb2Uz63esE/sbjmqdcQ6DpwpMqb43GnI24CtpAFRkg8uWo1dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T17:21:37Z"
    mac: ENC[AES256_GCM,data:KhJ2r7p8mw/7zkwVYqCKDV0ATsDDEdi3APxCOqEJe8UxlRjosrlCpQIB8rBBmaAGadB2sFD1c2Oq22EMF9PC0NFfIAF7cAO9IYl9cURXYt88O1onnNtFIbNk0mBVhAbomtWmVpVGPUxI2TZwS8XNayl1bvxpzkWiLcati0WOrIk=,iv:kpyHDvSc7+Aww/99srPUCPetWDsWGNI0SNL937bQ5jo=,tag:8ewjKfH6dKB1p/aEVV/lzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
