apiVersion: v1
kind: Secret
metadata:
    name: airflow-batch-secrets
    namespace: airflow
type: Opaque
stringData:
    SEOUL_API_KEY: ENC[AES256_GCM,data:AV/88+hhXe+sOq9FTA5kpVOk4P2qsnGSLTfQgp3s,iv:C1U71QCki3caxl1ZGX/VWwgZ4uOjCwZcOir6KaYYjdk=,tag:bzqGoKqb8pMrtASHndG+iA==,type:str]
    KMA_API_KEY: ENC[AES256_GCM,data:sXFdeuPZoiOF8PjOA6Fxkkmr2/Okl19LG0BPTS/GZ504e3l/Mdha4o0c8whM0rTz5rDtNHC+wf7zLICj+bjn92qdkG+PHnXZ2Aas5LEk2rPdNd93+OTpJcuxVmE1iub3aVXayA==,iv:ZxUsjRuVdeyJr/hSOae1hHtTf6WzBwbA/GstKi/Ykqg=,tag:9j2O//f+iwvJqmDL1gzpGw==,type:str]
    DB_USER: ENC[AES256_GCM,data:Ms4KIcjangA=,iv:y3FiiJoLTgdDbIS2ehN5ddhAe/GIrRnKxpoQgPISvRc=,tag:4OTc7r8pyoAkB1y8nkqFlA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3B+PGA==,iv:F2RqZ+VdfomPWDFDylu2LUxGCWar++kmVaURkFwS3+A=,tag:S6kor18WC4NH9nOLSHg8Ng==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaVN3NDVhOWpXZENRVDFQ
            RHhSQmw2N24rMEpiakFxVm5WOU5oRzlOK0RjCnZzczR5ejJYM29lUmpPT3ZVU3Ex
            M2x4aTNXb1NsUFk5V3dUWnVMeEtFVUUKLS0tIEF4ejgwMytYTjBzdFhzOXVROU1T
            Z3J0Wjh5amlwNUVhREwwVkF6WWRoZG8Ktwj//rYgWJWoBU/Y5C46PB3+g1L57uI2
            ETVmTAYY++uTugfxexS0oNsZ6gD/rwkwnu+gbimF2SL+W1lHTmMWfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:57:29Z"
    mac: ENC[AES256_GCM,data:GTQSvXHvvii0T2UxfuMQJbWbcg1Byk/iw+HbM7tuFGhZLn3mtDsdgAUFhxxfF+n9cONqGF5Rg4uxzK4rriZscq1VEBOqwEwzBgLjGpCh9Lv4R+54zeSo/KKwYDwiy8IEk2HipBx3wSZ9ZeFOAS07uCfPEdGR70P+4YQxjBFVIeM=,iv:AQMiEVR7SWfEuxQhrqvM+rOMIrxKXMmZK0m/KVlSAlc=,tag:/Kc52Z+WC0N9G6B8kNqt9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
