apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "82.*"
    helm:
      valuesObject:
        grafana:
          service:
            type: ClusterIP
          persistence:
            enabled: true
            size: 1Gi
            storageClassName: local-path
          adminPassword: "-DPT4vCpdKywvskG"
          initChownData:
            enabled: false
          ingress:
            enabled: false
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: grafana-dashboards
                orgId: 1
                folder: Spring Boot
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/grafana-dashboards
          dashboards:
            grafana-dashboards:
              spring-boot-statistics:
                gnetId: 19004
                revision: 1
                datasource: Prometheus
              jvm-micrometer:
                gnetId: 4701
                revision: 1
                datasource: Prometheus
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            retention: 15d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 10Gi
        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  resources:
                    requests:
                      storage: 1Gi
        # k3s bundles these into the k3s binary, ServiceMonitor will fail
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        kubeEtcd:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
