apiVersion: apps/v1
kind: Deployment
metadata:
  name: naver-news
  namespace: prodesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naver-news
  template:
    metadata:
      labels:
        app: naver-news
    spec:
      containers:
      - name: naver-news
        image: ghcr.io/sijunkim/naver-news-spring:master-e0b0c0c
        envFrom:
        - configMapRef:
            name: naver-news-config
        - secretRef:
            name: naver-news-secret
        ports:
        - containerPort: 3579
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
