apiVersion: v1
kind: Secret
metadata:
    name: naver-news-secret
    namespace: prodesk
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:I13ujtzLikkr,iv:JJvcUTYSXrnSJhGXFL4NU32khI7jRP1kLiAegrDUgwg=,tag:fh+QtzFYm4QbTJZXRfZeYA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:YnQdwBixJuyJ,iv:ReVP6T8Bx5URFdQG3KRXFZ67oG1szP/UtUEPUMKwvHg=,tag:fvgkGzF7e8LksO2vL64+9g==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:D6khIimS3DBz,iv:wtbUAMCdjwdBaomysSfn4QPWXVUntvaXbSwpvc/i6Ug=,tag:AIx+e5aKlfdNkalIiq1HDg==,type:str]
    NAVER_CLIENT_ID: ENC[AES256_GCM,data:PEF0loYsiVND,iv:jM7/Typ4kHn11X0Dpzu0yGmFclOEA9uv22X2EFNA684=,tag:EkPsR31izkxYnw1h78a+oQ==,type:str]
    NAVER_CLIENT_SECRET: ENC[AES256_GCM,data:BYt9GKk48hTN,iv:QADv+QMCcI5jc+hylKSLdN2VdZNILdubhC0479VJC1g=,tag:oNR+zvyStPc8HAcDMN5+gw==,type:str]
    CHATGPT_SECRET_KEY: ENC[AES256_GCM,data:gRjhNqFl3Tui,iv:d1PRFmHMrSQtJc0bejZqmzYN1vijPxXGAGnZaM8gB40=,tag:gcZSUW/In0buR5E/NSs24g==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNUZTNVRLNEJvRUM3aFJk
            TXRIQkk0L3JSWmZjSGl2SGx2MkhNSCs1aEI4CjIxL3B4cWN4RG1WRStoQktvZlZk
            L2lCL0J6UzlTNkpwUHBhU09ZU29vWjQKLS0tIGZ5a0xJSTN2TmhaKzcwb08rZ2x3
            dUxTKzRUdytpU0IreUVVclE2TEUxcEEK5Rd0wtSHnKW6tRg0aWsYXUVlPzM9xFNp
            jxuSN1lBIfS4inMXl4Ld5rtfYNgXuxTFAXSidGdXyLYDlJRKdA0ITw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T04:12:53Z"
    mac: ENC[AES256_GCM,data:HATXkQxEDkfKBT+A7IaPhm8SGnErBtMt1+13CvDT80PBudIsgKskoY6UtlO0j7P7z0+J/YFzcWEw+Z6NjR37ibI4FiR4bZWrOoZ5PA9k76FdmxhKBcW7+kGGrMzAjU+lA2eOMFjbjrMaGj9F88aI2yis0VwYlO9/fIdkiaBDlVM=,iv:lyp1H61AC6h7BUdpQVVYTpXnb08T/2igCTNnAxjWNP4=,tag:EuP98P9+IvQCA3XcChm/MA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
