apiVersion: v1
kind: Secret
metadata:
    name: naver-news-secret
    namespace: prodesk
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:/TXPUo8ZOf0=,iv:UyPPuSe/0RoBjIhw9sEm3iXkMU+0T5PC4zPbO6ZIQFo=,tag:5XrJiUwE1MG8HtEWXYIUFg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:1O0hWQ==,iv:91ESdwhW+6uAsG/WV56cp7sNmU8X5QpcODxUv+T/gNE=,tag:WfdAYOmuBKBbSmVrxpsjfA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:/XPlraob23I=,iv:KQanefuyTt91D30UHEfe08CNzgTi32finixX4njNVDU=,tag:u3zv8Ar16VI1uyaBxhRcCQ==,type:str]
    NAVER_CLIENT_ID: ENC[AES256_GCM,data:auovRDBow9eIq6qUfhqPdeO9B84=,iv:hIF9uq6hqXtjgYu8tonAMAPdwcIRrshF0yalJoA/3Xw=,tag:fxFPPSu667fETlus8iLEvw==,type:str]
    NAVER_CLIENT_SECRET: ENC[AES256_GCM,data:yiwV64QlyW5bcQ==,iv:DbBypmmr4lRBOFvjN9lmD56V8lKgzVIfelRKPRffCSU=,tag:S8/3C4tQspy7WhWCMxweyA==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:XnSq6KVdi0SPGuPYIYjkKvdiFtDCboLO64FpUD0TBtJtDqurBew2OyQvfeOkxC7MNgrXrTAALss=,iv:z+zryVG5dSBRImsS+1naKFqB5OEeAv/fK7qL+WGmh44=,tag:IvnOs6lQPpd6DEv/GjwALw==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqek5uMjJwRTJNZmpjSkYx
            TUZYN2JUZXQ4ck56VTc3WFNacWtPbW1teFRnCi9DUEU5YVJ4bExIVHB3K3lDSkla
            LzNBQjdBQ0NrL2dWSFJIZXlTVVVQaDgKLS0tIG9ZMUtTYXJFMDZ2Z2VsNEtwZVB1
            SDFSdndxYnloWC9QTHRCelZpUEg3N1UKrcdfygXrRfmhElrnueMtZzIeGeIC7HSO
            CuV9p5yapCkYfTyzfPXi5wakcNIJWHwrIUneGx3MwwQFDpczfA0QZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T23:56:01Z"
    mac: ENC[AES256_GCM,data:huHhoCf0qWJUBfF8IHFYk21asdLXd/R3BjTVQ7e6VvyLg/deidLwySOf0xJltCGf1jAStzYNU36RCUW6c0tdpRmsbihVrpepcP2RKGdIJJoigUFKiAHeme3HbNtKWOF4q3q7CZUl3nl6j84sEzt+TJKxWCm8iAe2/BmdnhtaHQ0=,iv:1UftMn6/8PKxs/VpYs336Egx3WCJDM0sfNFvBnXYoq8=,tag:2ZguHGYe/TkMqFcKgb78og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
