apiVersion: v1
kind: Secret
metadata:
    name: naver-news-secret
    namespace: prodesk
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:hHztpZbJSA8=,iv:kA2XGFRzCy9tWH9OOUIb6s4Eo3DfnArp7yY3uJqJI/I=,tag:l1JTGvFj00tvVxgGQcr/Rg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vL3ayg==,iv:bmoRaA+IjgUQa6JN7lsHvKrVupr831nB4GqiychOsF0=,tag:xag6J4lD6vrl3IQG/GkI9A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:fN5lvCPiYjE=,iv:E/Vb5hlp00LNb/1kPQeWcOO1XLBk+WfeVu9uXialtfc=,tag:oDluIER9rS6gEZLEtFKnlA==,type:str]
    NAVER_CLIENT_ID: ENC[AES256_GCM,data:ldPDYDkxoveAD9dzPLcGd3aBGtQ=,iv:EuqLtO/YqVn1TQJiaKoDW5yb2WAmEbhJD9VchU3HpNE=,tag:YBlHFHnUQmNJSIQFiVI1mA==,type:str]
    NAVER_CLIENT_SECRET: ENC[AES256_GCM,data:qb78aTgUmyeLdQ==,iv:qLOw0FkA8hg4oIrwuT4l0jvOloxMn4AYUTxwbsF4Cfw=,tag:Ne7SCZd7LKdcxF0jaSi4nA==,type:str]
    CHATGPT_API_KEY: ENC[AES256_GCM,data:jBkmb4pTHJzaJclvcjbTV3CndiVOTHaOEZ07TR1eDv0IYqTjDiTKav5B5Icff6JaiHyuDxCUGcHqKjvgN1AaHhSipF20TX//0T5whslDl1rtteTp/i0/MAuf+YeKdWJnCmxcxGLdFNnGoA91tq+/1TYWiRc1EDj6tcwtf7W+WVSu8mNxfp9J/agAnyW6nL9n3OvO9cOQ36f6GLkzO5L0nfYJJXc=,iv:D41ISX05fhOTjMqgvy1Xe2ytXVdm5Mf2zthkkc3RKyI=,tag:VYqwvPZyDEPrnj9VxLe/Cg==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbHFoT0Y5OVMzYytQcUoy
            a3ZMNlIwdkljVmJmNkovcXAybUY5eDUvOXhNCmd1dGNOaVdWVU1MOHNKVHR1TDcx
            dGdwTHFBRThEcVQwUmNVQTR5WGRvbGcKLS0tIDVUVGViZzRqQ1pvMlFtaThpclkv
            cTF6M3d4alRSYiszMFozbXZUYkpzSlEKSHRKv09X333m00TmJ3EY4ID6OrKgRFER
            pYckBuVgeGUnxtP/9h8IcLOwBueuS2DK4NarnZDBZh4kDqapDWgUSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T11:07:26Z"
    mac: ENC[AES256_GCM,data:IMUGIr4g0DuUdVXo6quKu6dKTpcDVfClletw8ytOxvdFRMbvXHBTpXR6vNpTo9+gLDPMVHgRrKCB0tYli4O9Q7j+yNlOHN4wgAhI2JVFl2TiihUOeSS62mw6rgQbbywtHQsH/srdYzhscw3aU3OIiTTwgwhF3djJ/En+XCWXQJM=,iv:BBKbQ2niAJ+1unNIwVi/jPBNGrH6MmqXjViDU9bWfY8=,tag:aTaeyzfJs4DwL18eb9n3Bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
