apiVersion: v1
kind: Service
metadata:
  name: naver-news
  namespace: prodesk
  labels:
    app: naver-news
spec:
  type: NodePort
  selector:
    app: naver-news
  ports:
  - name: http
    port: 3579
    targetPort: 3579
    nodePort: 30579
