apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: dama-prod
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:GurOlzNECdaex3wngjRFhRLTPvBoDJr9uQdaFWm2TqzPuqxqGwfPU/6bAYzPASUkBmNWSQibN+N3IjJQE7dlbiPagvrND3r2bEagr9dDN2e9HlagxCZkbq9xPl3fqrth9nVwo2euTR2jj+l3zVe7zKQliZwhp4D1Wrs/zvCtw9aqcDHAPTN0/3LCEJsBmWIpToZvwdPNlDrrqHuNMsbi3inEPoYj3gUWuQP8U6v/+ifzR8zdAzH/N6V/mTJGiu1F7pAXLkEgZOrQzYYroFdJgIwm+FbPdIC4gdAHhQEwkTfbavyerEvg5hnQhKBjI6UV,iv:C4kJcg7eR2j0RIuRGa5ncE6396BIl3W8fHhUIlsT7yg=,tag:yJNI4nL9Gc3IAXZa0ESXtA==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWU9WelF3dU1WRDhrb3Uw
            OGVmUVNFUnhHNVpGMUNxUjNxVGcyL3k5WWhBCndDcjdRMXFkYzdwYW5iUnllbjZl
            TnFobU1EN1VreTBlN1AweGIyTkVhY0kKLS0tIHROVldHREdjMy93Ymw1eVVjTVNX
            dkxJT2hjTlRnb3Y0N3h0aTU3QmJqZ1kKTlPKZGJ4nBFw+/FEuu+6exkZdapys3hh
            2tKHmPsKlQT4FaCIM6RLyPa0X0CQkQdNM7044nRkzl2ttNN9DQgtKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T19:49:28Z"
    mac: ENC[AES256_GCM,data:YwZZhjg3tcjthHoveMShadz2SL3FXaN8rSm7IaxWVrhdZ47KM4OeBn8kJA5A8P/lj9tzn7kMMFwQagh7n6x0bg5ryxwdE1NwzoxjtnXZZxuWfmVngctUPE/DvHz+DopMrPs7vtEvXcTy3UK/C/UYR1zemvmq+dwvJs8DAJNpw5g=,iv:sKb5f0b6izl39sh/Dk1B9A0Gj0RYFvncgkNy3G+GRF0=,tag:pifFDFKNKxTAvtACeneiwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
