apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
    namespace: dama-prod
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:XSEmfhstLsZA6d4oJv6lR16NJfcvyoes6ebeSTYhLnc=,iv:yR+JCevKVBzsawAK9sj23Ynsv/1unzIIOmWy5XnWu9s=,tag:aQYXcCd0Gp4+Ss46VoqCCg==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNlBSMTdYVWJmRzBqektx
            S29WbUgwL1lVOGlORURsQkE5c0N6Rm91ZWo0ClhtemwzWEllaVVzOG5uMkhtRTEy
            ZnJkdTlTVHBIMnVkQVN3TUI4TkI4ZUEKLS0tIEg3SEFuK0VXQUQwUmNnTTBRWHll
            OThVdDRkRmVmSks2VmlxWHNieFJhNGcKpVJyIOvQ38ga2QfCDqRMQutb7UeBicGZ
            J6KI5o3+/wVVQPr2POItDPLeVKFKx/x5CMCPIh+FdxTLMgefUOMEpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T19:38:00Z"
    mac: ENC[AES256_GCM,data:nysr1CN7Ptu4mSoSbhkMI0ty0uAQQ9sIQqLAaKM3vgY2F2nygXBfh1mHbst7XJMRTVZlSFrOiFtyvyQMSEoqlWaJYK6Uy7J/pKObbv/9pjDEZkPUQE1z5cB2IjXay53J9uI5Q2gspYI3VdkcaUc77crMVcBRG9zHZNYPVynANbc=,iv:H6l1cHmvx5YGgAOzIyK5utpElyjW8ZJbN2RlUepgi6c=,tag:5Tc3+xRfduZKdBelQYr8vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
