apiVersion: v1
kind: Secret
metadata:
    name: dama-api-secret
    namespace: dama-prod
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:YgzyUC8WxHNgYoW844J2K1egskewNhp8waDmcqCF1nUmmF56S4NfA1KHLY7Ik2o3mq3s0jA=,iv:UoA77A10MkjUAvGLCm10/SCA67ETNttWIxio5ehXrnI=,tag:LtPM4PQKgIsZikeDFFV9kQ==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:e5DjvFgPUPmsxvQIjWVu8ibVAeZkEYCOiq0OKEk4xS0lq8D4ltv2fPQXduYJeCJLOPgr3AMLOGI=,iv:UMpyRQ2JUisQv1R902fNwI4T9e1aqYmkTu+h5CIc8fM=,tag:IZCOui2dngFDnKGTEK0zSQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:fU5WfCwz/S0SOsNSkhl+ncOzB6EKFCA6/A0/OVTGq7pqkOEbcUMTiGbTSUQ4Ct4j1PBS3xBMoPa4Badh2F7Zel/bCxJyqHMJyg==,iv:3n8gqirsY4EyzOBUrBpXpEX93k2+p/HfHC0yD8VCFPo=,tag:tcXFdXIT0HsEiTHXkFByfA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:asXIhSZG/YajWKVeGkT5Vo2t+PiBz7Uwmj+XyLOgMRq+vQSDQUEZwmgMXA3ENiByqkPT6wHjsNIRH91modnU5A==,iv:bNlppB75XPCQZ3RFdLcGssOUy9LVq/xFBxgikdNoBCM=,tag:BGruPOlohdOO/PZqntjj4g==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:z7yz9UzsUFESkSF5RPPbdi55rrlcddPOTQ==,iv:Pbocd+tgyFSJRcDfNU1rZhOn17sDc+Li7oQHSoMc8T8=,tag:IA59dMPqA2IJ+v3odol+Ng==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:R6457WAt0ANy2QAjnggJxA==,iv:c3qzNUi4Z59N5eS7vvmPuvhaFoX4dt/YoUDp+Ph5oSI=,tag:6fopXgbHffipn5jy3DgFpw==,type:str]
    SLACK_WEBHOOK_ENABLED: ENC[AES256_GCM,data:aq09MQ==,iv:kpNQMsyy4vslLbrUB7T3Q5RUKqxm2sh3b/rokcqzcZY=,tag:QtczF2tUzSTW/gwmquKcgQ==,type:str]
    SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:5kK+wkSI4zYsADRkZrKdMcFehcoUBLxJsQxbGcaj4fUE9eAlWKS3rBO2g8u51TIbUoelJYrZp1vjkfCTUbfTzR7b2J3VQPfjKsYvl7r2SA5p,iv:76lPDlUmaM3rHqwmMoO1MoHjpcaH2LHBeA2DrXT1nH4=,tag:YSig4ZY95nUL6S3eKgnPKw==,type:str]
    APPLE_TEAM_ID: ENC[AES256_GCM,data:CUIsOxGyX5c1YQ==,iv:nxNJ1Ljhv+4WVMRbb/GEXx50I2jLUZw6qKU+Nt77Q7o=,tag:2dF1MntvP1x8X4HwADiUww==,type:str]
    APPLE_KEY_ID: ENC[AES256_GCM,data:qVM1n4vNiEc5Fg==,iv:2w0Ve+bfZ5NKGXcPyHoeWzzgBYIydKSsO8lEkOA4upY=,tag:f61oEPXZm0XWlk3EX92hZQ==,type:str]
    APPLE_PRIVATE_KEY: ENC[AES256_GCM,data:slLUbdvausJfC+7qkj5tWColU+YxyyxXWMEAysVCuVLHbEWBkt/AGOqpbpTnEF+mopZmggUkrgwGmb+ieNm1fNPJi3d7UFPLKqFGFUVuA+iMhlgxhu8HzbaJib9AUGZapsSoq+WdA5cQwCcvDcbNnDxm4P6CxNL1heL9mDCop7ZIg8J6lJbwHD7x/Jv1c6xGKOuOTJguNUsc/wMHBQ2vRlB9qzk1P1+U4ZBALAtwv3wi6NnUXfUDqbmgaKKOy1e5yvlBieEus4BYCTlEvgLmtt585Lcnjn38fUX0Ff5OXhAJtn/EOxjvYGPZozv6KFoTOM+q37oyqsMNoWBJQAqTprw=,iv:cEJa30pEU5MN4C7P+NMvOtXUks4PsaI8PMkPay14+Uo=,tag:KGe29YWfvxxvgeR5SDnR6w==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY2dUd2hLWFRzSFlScTA2
            U0xycXFaVlZvNmFLS3doNklTOGhOT0gwbGcwCnJ6RmRnNVlZRlZTOWp0WHNZOW1R
            NEMrNENvaTdkdEpmbGVFdG5mS0NmdVkKLS0tIGRvRG16czRIUkIyemJWdjZNRFpj
            dHFHc0xCQmFMTURHOGMrNS93MzM1bnMKpsYnHzdElHzERZGGOx+G9rfF4Zw25/+Z
            EXtl9BoWiCA+PZ/xvzG1U9w8Nz30qitfKWlYFLiEbhanE8MRF3d6zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T15:36:22Z"
    mac: ENC[AES256_GCM,data:d0KCicYgG9COfJnTJG2uXBO/6IN4a15LRCMrOWHgSI+jVsF8zHZ8M3ZghTT101NSUb6OokekV4AMdyyF7l/pfSuYIKdbP/TxyQZIuOKlld4WGAMXgFiTflfN4BtZl4co2OiHYP50Eb7xuTCNLrOHA8KHDd4akkPbAMdewuMKqKo=,iv:oCC3fibjQAl2GH9IjM1H1oxv7zln1S4mszSb338nRts=,tag:wUh7h6aqPgU+VJmwdbVIpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
