apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dama-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: mysql-prod-pv
  resources:
    requests:
      storage: 10Gi
