apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: dama-prod
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Kh++Ub97eaWdn/jCJ7u273udhN+la8TAPeExzG54xX0=,iv:vufwVUaU4hB182BpPXeHFyBu7BOAt+LSquhsH/3N5Bc=,tag:ark59BQjLcHGrk7yVOtuHQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:W308tg==,iv:W3x7eOvlcgcK9zs/rKQ8Wad0pGxDg0/k9zdGKMBNCi4=,tag:cGy4V2waHrReLdBeT9vMvQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:B6M5OQ==,iv:rvQsE5zLGSBdB32wAbDbZd/25b7cvRUbLLP3uAVIj6s=,tag:/VvRatSzM+nC+vOEuxUR1w==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:8MLpPXd78IL6PZs16+DwEeU7JZs3EMSYHpIy+1BMQmQ=,iv:KN+ep+AIEJ0lKRHuUHCYsRhj4HySmnjsSB4dYd8yu+4=,tag:ETXaZsOk9QP4F41BvbjKcg==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVStUUis4eVpuRG5IUDAv
            SnlHZUhMcm1CbUhnMzdxUURNRlVDMGxoU3d3Cmt1OVRZcTBLcS8xL3VsakR1dHcr
            ek1Fd1VVeEFFK0VLOHArVG5LYnhpejAKLS0tIGV2NER6a1JUZGp6R3EwS3cwR3ow
            enppMXVvY0xYRXQwcGpKTUY2bjVTblkKOZQzqLelrB2YQNBdgeZ4gjz28qYHuVeq
            rVzJqMRmWwaiil4i2dcJFKYy5n5RyuUkNE+MtsBfPYSl0Ya2Cn0PRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T19:21:54Z"
    mac: ENC[AES256_GCM,data:oj9t8hCo0PSergO39/ilS4WxNdsYrYpxm+jw+yOuyrQTfHp9nqs+5odiibyjNHKLaP4nLEpx0qwtFh+I4aWbpHIdnLZOsLsq3VA8mYvuRniFeZz43wLO1egA1n5+fjjQ8FFwxEJ3sj9nvJDnnvvgO6eWffJ/BFAG38aNWp95Zbk=,iv:xB8UhyuBjCYtR2Jqv8yawZtU5TJSPGRwTPCWGMZRrfs=,tag:BAadYu1CIVcoRgso5X3SKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
