apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: prodesk
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:vHmvb2qCl+GU,iv:vkvg5ItJg2s/3anEC1ZsuCjsXyP25o1tUJrCX9VY42I=,tag:scgffNYrhIX/2tjumb6Gkg==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:a7JgodEolQZl,iv:0dwla3LIk9i9bTp/46kuvU3dt6jvVyd7YYAeuzvUxS8=,tag:s7RkBWRAEscB8COLrkENLg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:lyEP4kbub7YP,iv:s+62E0pstdrUVVartgR36TNAPcNC8PaKB7fntkyc2m8=,tag:LR9UXrfZeJTMhtFtiIzaMw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:xFNBafuEqHQ6,iv:q4N+AEWWzKYMqXbu5oYOll1N5uvB6EpV/nuejhKYYzQ=,tag:GEkV7GtzwYdb0xMGetuJkQ==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMGFUTHZrUDFYY2xFQjVT
            ZTBIRnhLZ09SRStlUmdONFBKb0djM2ZLU2hzCkJ0NTJxdWY1NThpQTlzY3ZQS1F5
            WTltOHYxVzNCeUJYRkVCSVB3d3BhZzQKLS0tIEVOYlh0QWk3Rkx5NG92aHhzKzBF
            QWNacGo5WlZUVlBibW44dkh3QzBpc3MKhVhW3mRCsoxlWaatknB0BLYRERKu4Qci
            Winl/f5iAueQrCp+c0lMC4Q/IEdlj6fqwc6MRpB4YQVBGUCCD/xT4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T04:12:08Z"
    mac: ENC[AES256_GCM,data:X+80xtArP6LkqZwLfCXv27PtgfUF88NRHEb1jRY/c0wHPiUxbbovnQwY8BBJwp3clb2jMTTmlB9Bi2sc1yptU+sfljOOQkozTGZ/Xl/4XZIOuIjQVH7fp0CTZXvekXANmg+6nQwKcrVEOnUi6Tk05mVVVe9bSjbWkijQw+8aqrQ=,iv:FW0QyCNxjXSeKyABSm2KCYQBODQn0h4uKrlIcOy/eAo=,tag:oNI+SGkiCAQCaJz8nnb9gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
