apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: prodesk
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:EuHZkA==,iv:IPwaXC5b3V2HFiQ0IV3iEylby4GWlbUr9TW/gfvjPwQ=,tag:oTO59ECDtQ7TS6QVweKBTw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:jACAgAUfjPj4dTVPdq0=,iv:ECphl5YTlf8IjPRHDVBqs9iTJh6tAZoMeHIo/jQZ7ss=,tag:gClkR4JPErLNcElRO8cBfw==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:66dfvDjdXF8=,iv:l5yQW9dr+RgWq+3kw4UjsjyJn1raCspTjmL+zDFRf0U=,tag:y+G0Xqe/B5C93lgpYKG8uw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:wSEHeA==,iv:G4fIxPCOv32g0FVKu5taJrlq+rjxZakshlH0rKRiqyo=,tag:lXVEHHqFrWax7B9HPhdmhQ==,type:str]
sops:
    age:
        - recipient: age1pkq2sx0xg0sjpr57t9yqtar5sg255fafhah9kdc5luh738xzk9psc4pkkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQWFUcG1MZG1VRjJOd1R6
            V041WGRYc2MrVDgwTnF6ZWdCcmR4OFdKUUJzCk9CY1JGWmRjM3FLdUZqK0RXVUJn
            dzhvdExkeW91cURGbDRsWW9GZFVPUHMKLS0tIG9nci92VkRHVmZhY0RMRkxnbFBQ
            d3pJY1hIeUc4V0p1L2QwNlYzWUw3VzQKxHF2O3ay3SVS5j+UIank3UZ/J+bmI61Y
            vJNxFreEadj2yjAMd/eF31jNufZ9FpWRaeGKBlZR8+3K/XoWvwN+WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T11:07:35Z"
    mac: ENC[AES256_GCM,data:TYBZSSaTkf2wU0KUqSRlKkW3GY/HOqQ0o2X8cBHSx0LOf5KoxZ7HhoPetVNIUxfbmf6bj9kcYlRwNi+HzBZ9+5yAxTlbkqDeacb42/jVS5GPiKPuXlsk1bYoeTF2qU/nuiGgx5L5uoVIzp/zvec4jKW0Q1VN/vcOK9FOR4gQOsA=,iv:KL7cGfx4/YH4NdK0V13LRc6w3D0OCIGXwdEgKM55e+Q=,tag:vpFGVaG7Nm6IhxPKVjU+0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
