apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: prodesk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: elasticsearch-pv
  resources:
    requests:
      storage: 10Gi
