executor: KubernetesExecutor

webserver:
  replicas: 1
  service:
    type: ClusterIP
  defaultUser:
    enabled: true
    username: admin
    password: changeme

scheduler:
  replicas: 1

postgresql:
  enabled: true
  image:
    tag: latest
  primary:
    persistence:
      enabled: true
      size: 5Gi

dags:
  gitSync:
    enabled: true
    repo: https://github.com/sijunkim/airflow-dags.git
    branch: main
    subPath: dags
    wait: 60
    credentialsSecret: airflow-git-credentials

logs:
  persistence:
    enabled: false

statsd:
  enabled: true

