executor: KubernetesExecutor

config:
  webserver:
    default_ui_timezone: Asia/Seoul

webserver:
  replicas: 1
  service:
    type: ClusterIP
  defaultUser:
    enabled: false

scheduler:
  replicas: 1

postgresql:
  enabled: true
  image:
    tag: latest
  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 30432
    persistence:
      enabled: true
      size: 5Gi

dags:
  gitSync:
    enabled: true
    repo: https://github.com/sijunkim/airflow-dags.git
    branch: main
    subPath: dags
    wait: 60
    credentialsSecret: airflow-git-credentials

logs:
  persistence:
    enabled: false

cleanup:
  enabled: true
  schedule: "*/15 * * * *"

statsd:
  enabled: true

